### ISSUE TITLE
Let's run Community Ads

### ISSUE THREAD

**Issue by feross** [feross/funding#14]
ReadTheDocs has an interesting idea called [Community Ads](https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html#community-ads). From their site:

> There are a large number of projects, conferences, and initiatives that we care about in the software and open source ecosystems. A large number of them operate like we did in the past, with almost no income. Our Community Ads program will highlight some of these projects.
> 
> There are a few qualifications for our Community Ads program:
> 
> Your organization and the linked site should not be trying to entice visitors to buy a product or service. We make an exception for conferences around open source projects if they are run not for profit and soliciting donations for open source projects.
>
> - A software project should have an OSI approved license.
> - We will not run a community ad for an organization tied to one of our paid advertisers.
> - We’ll show 10% of our ad inventory each month to support initiatives that we care about. > > 
> Please complete an application to be considered for our Community Ads program. If you have any questions about our community ads program, feel free to send us an email.

What do folks think about this? I'd love to direct some attention towards community conferences, non-profit organizations like EFF, etc.

**Comment by mixmix** [comment]
I'd love to lend support to rad FOSS projects. this could be:
- sweet p2p projects like Scuttlebutt, DAT (don't have big marketing budgets, they didn't go VC/ IPO)
- little [TIL] snippets about core modules we all depend on but don't get much love

Could be quite easy to have an array each of `sponsors`, `community` and ensure e.g. a 50:50 split of sampling likelihood from each set regardless of there size. That way people see : warm fuzzies + companies who you know are supporting warm-fuzzies.

**Comment by feross** [comment]
*Reposting [my comment](https://github.com/feross/funding/pull/9#issuecomment-524590087) from https://github.com/feross/funding/pull/9:*

> @kemitchell funding is helping to pioneer not just the idea of ads in postinstall, but the more general idea of making funding issues visible where consumers would rather not see them. It's normalizing their visibility. Consistently standing for the fact that there's nothing wrong or shameful about that benefits other funding-worthy developers, too. And not just those who will or might try ad-based models.

I like this. Still, for pragmatic reasons, I want to offer other contributors (i.e. my friends and colleagues) an easy way to indicate that they are contributors. I shipped this as `OPEN_SOURCE_CONTRIBUTOR=true`.

Perhaps, this flag can be used to show contributors a different set of messages? For example, if we ship Community Ads (as proposed here: #14) we can still show community ads to contributors. And other PSAs about the state of the project, funding status, etc. could possibly still get shown?

The nice thing about this flag is that now we can now choose to show different messages for (self-declared) contributors, if that's what we decide.

**Comment by feross** [comment]
I've reconsidered this idea. I think it would distract from the primary goal, which is to fund maintainers.
