### ISSUE TITLE
Make it clearer that your sponsors have pulled out

### ISSUE THREAD

**Issue by traverseda** [feross/funding#17]
Both logrocket and linode have pulled out, but they are still mentioned in the README and the issue that was circulated on social media. I don't think they want to be associated with this project, and continue to mention them in such highly visible places is doing them a disservice.

Personally I didn't find out they had pulled out until I went to get a refund on my linode balance.

**Comment by modeco80** [comment]
I think he indirectly did that with 03937d3

**Comment by traverseda** [comment]
The readme states

> Currently, these are Linode and LogRocket. The sponsorship pays directly for maintainer time. That is, writing new features, fixing bugs, answering user questions, and improving documentation.

We can see from those commits that the sponsors have pulled out, but the readme still prominently states that those companies are currently sponsoring this.

**Comment by modeco80** [comment]
@feross Are you actually going to do anything, or are you just going to sit on your ass until they start screaming at you?

**Comment by kemitchell** [comment]
What are you two doing here?

**Comment by modeco80** [comment]
We are waiting for a proper response to Linode and LogRocket pulling out of sponsorship. Not only has he not done that, he has failed to communicate on why he made the release v1.0.8 and the commit 03937d3.

**Comment by traverseda** [comment]
> What are you two doing here?

I was very surprised when I found out linode had pulled out, so I'm trying to make that clearer to other people, and I'm asking the maintainers to make it clearer in the README that they're not currently sponsoring this.

**Comment by modeco80** [comment]
>I'm also confused by your question, and why you immediately followed up on it by blocking me so your wouldn't be alerted to any kind of response.

He's a software ""lawyer"" yet he fucks it up so hard it's almost hilarious

**Comment by traverseda** [comment]
I understand your anger, but lets try to keep this civil?

**Comment by modeco80** [comment]
I think that civility was lost when the maintainer of this project called someone who was conducting themselves as calm and collected "entitled" when asked why he thought that the maintainer was entitled to spamming postinstall logs with ads (#7).

**Comment by traverseda** [comment]
I don't care about that, it's just good tactics. You want to look like the good guys, and in the instance it's really easy to look like the good guys as long as you don't fuck it up.

**Comment by modeco80** [comment]
In this case "the good guys" could be anyone not supporting this nonsensical "experiment".

**Comment by mixmix** [comment]
Closing this issue. Not respectful.
I'm on mobile and wish I had better moderation tools here. If you don't like software, stop using it. I'll pass on the message to Feross about requesting clearer comms.

**Comment by traverseda** [comment]
@mixmix There are definitely some people who aren't being respectful, but the issues is valid and **you need to deal with this**.

[This](https://github.com/standard/standard/issues/1381#issuecomment-524578926) comments says that "This ad was not paid for or solicited by Linode". If that's true, continuing to associate linode with this project is a *big deal*. The kind of thing that leads to real losses, the kind of thing I suspect you could be sued for.

If it's not true, continuing to associate those companies with your project when they've chosen to pull out is a very shitty thing to do.

Yes people are being shitty in the comments, and if you'd like I could re-open this issues to clear that out. But you need to deal with this.

**Comment by feross** [comment]
@traverseda See my reply here: https://github.com/feross/funding/issues/20#issuecomment-524602069
