### ISSUE TITLE
OPEN_SOURCE_CONTRIBUTOR variable

### ISSUE THREAD

**Issue by epicfaace** [feross/funding#18]
If you don't do tracking, then how would you know what percent of users are turning on `OPEN_SOURCE_CONTRIBUTOR=true` (which might affect the reach of the ads)?

**Comment by modeco80** [comment]
v1.0.8 essentially removes any reach, so I doubt it's a concern.

**Comment by feross** [comment]
There is no tracking in this package. It calls `console.log` on a formatted string. You can look at the code to verify this for yourself. If OPEN_SOURCE_CONTRIBUTOR=true is present, the message is simply not printed.

The sponsors paid a flat rate for their message to be present on a specific number of installs, regardless of how many times it was actually seen by a human.

**Comment by feross** [comment]
I appreciate the thoughtful discussion and feedback. I ended the experiment last week. I shared some thoughts about how the experiment went from my perspective on my blog: https://feross.org/funding-experiment-recap/
