### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by Toxoid49b** [feross/funding#19]
The current version of the software (1.0.8) contains a serious bug that may impact the usability of the software. This bug causes the software to remove all advertiser messages upon execution, rendering the software unusable and pointless. Additionally, this bug makes it very hard to do speedruns since the speedrun is over before it starts. Thank you!

**Comment by kemitchell** [comment]
Brigading?

**Comment by Toxoid49b** [comment]
Don't know what that has to do with the bug but the software is still broken can you fix it

**Comment by kemitchell** [comment]
:man_dancing:

**Comment by Toxoid49b** [comment]
Is that the dev who will fix the software?

**Comment by traverseda** [comment]
> Brigading?

It was covered on some social media with a lot of readership. You can see some of that off-site discussion

here: https://news.ycombinator.com/item?id=20786981

and here: https://www.reddit.com/r/programming/comments/cus0zu/a_3mil_downloads_per_month_javascript_library/

**Comment by Toxoid49b** [comment]
Honestly someone in my Discord server told me someone was trying to put ads in the terminal and my almonds were thoroughly activated.

This whole thing is just really scummy in my opinion and it makes me worry for the future of software. Shit like this is why I'm honestly considering not pursuing a career in software engineering and instead just doing it on the side. If this is what the industry is becoming I don't want a part of it.

**Comment by modeco80** [comment]
I also came from the same Discord guild, and as soon as I saw it I figured it would probably break down in under a week. Safe to say, my expectations were not only met, but overachieved.

**Comment by kemitchell** [comment]
Which Discord guild?

**Comment by modeco80** [comment]
It's a private one.

**Comment by Toxoid49b** [comment]
Private one I own. Just a group of longtime programmer friends pretty much.

**Comment by mixmix** [comment]
This isn't industry, its commons! Closing this issue because its not very clear that its a constructive or genuine issue. 
If it is, giveus some more specific details be we can open this again
