### ISSUE TITLE
Out-of-the-box TypeScript support is redundant??

### ISSUE THREAD

**Issue by vko-online** [feross/funding#2]
> ... we'd like to focus on is out-of-the-box TypeScript support in StandardJS (one of the most common feature requests!) ...

There is [tslint-config-standard](https://github.com/blakeembrey/tslint-config-standard), which works pretty well tho

**Comment by feross** [comment]
Nice. But we're talking about making the `standard` binary automatically recognize `.ts` and `.tsx` files and automatically using the right config. The idea is that you can just:

```bash
npm install standard
standard
```

And it should just work, no matter if you're using JS or TypeScript.

**Comment by vko-online** [comment]
Didn't know where to post this question
Where is your AskMeAnything?

**Comment by feross** [comment]
I don't have one. You can reach me over email or on Twitter.
