### ISSUE TITLE
Did linode solicit/pay-for their ad?

### ISSUE THREAD

**Issue by traverseda** [feross/funding#20]
[This](https://github.com/standard/standard/issues/1381#issuecomment-524578926) comment from an acquaintance of mine raised some concerns that linode did not pay for an ad. Is that true?

They say a linode senior support staff member sent them this message.

>Hello,

>We definitely understand your objection to an advertisement of this nature. This ad was not paid for or solicited by Linode. There is an open issue/thread regarding this advertisement on the package's Github repository.

>We appreciate you voicing your concerns about this ad, and I've passed along your feedback to our team who will be investigating this matter. If you have any other questions or concerns please let us know.

>Best Regards,
>Tim H.
>Linode Senior Support

Was Tim H. mistaken?

**Comment by feross** [comment]
I expect this was merely a misunderstanding on the part of this support agent. He probably wasn't aware of the facts.

They have public tweets ([1](https://twitter.com/linode/status/1165421512633016322), [2](https://twitter.com/linode/status/1165422322481860610)) where they say they've "reconsidered":

<img width="598" alt="Screen Shot 2019-08-24 at 10 32 06 PM" src="https://user-images.githubusercontent.com/121766/63645989-141cdd80-c6bf-11e9-8d9d-0e70096274a8.png">

Linode has been very supportive at exploring new ways to support open source. It's a bummer that this didn't work out, but I understand and don't hold it against them.

**Comment by traverseda** [comment]
I'm glad to hear that.

I don't see any reason why this issue needs more visibility, so I'm going to close it. Hopefully if anyone else has that same issue they'll find it anyway.
