### ISSUE TITLE
Make it clearer that linode/rocketlog are not currently sponsoring this

### ISSUE THREAD

**Issue by traverseda** [feross/funding#21]
Re-opening this because it's important that it's seen, but the last thread got too disrespectful.

Both logrocket and linode have pulled out, but they are still mentioned in the README and the issue that was circulated on social media. I don't think they want to be associated with this project, and continue to mention them in such highly visible places is doing them a disservice.

Personally I didn't find out they had pulled out until I went to get a refund on my linode balance.

If these companies don't want their name associated with this project, it's important that you don't say things like "currently sponsored by linode".

**Comment by feross** [comment]
Fixed.
