### ISSUE TITLE
Funding source suggestion: boss bounties

### ISSUE THREAD

**Issue by chrishiestand** [feross/funding#26]
Hey Feross. I've also created an experiment. I created boss bounties as a way to help OSS maintainers like yourself get paid for your valuable time. My margins are small (read: pricing is reasonable), I'm not doing this just for the money.

Boss allows you to ask for a certain amount of money to fix an issue, and multiple people can contribute until that threshold is reached. By default, bounties are automatically charged when the issue is closed via PR or commit.

Please check out the free boss github app:
https://github.com/marketplace/boss-bounty

The boss website: https://www.boss.dev/

And the intro youtube video: https://www.youtube.com/watch?v=TJNOlpTPLsw

Please let me know if you've got questions or comments.

Oh and since you manage a bunch of npm packages, what do you think about https://tidelift.com/ ?

**Comment by feross** [comment]
> I created boss bounties as a way to help OSS maintainers like yourself get paid for your valuable time

Neat project! Looks like you only have [2 open bounties](https://www.boss.dev/issues/open) at the moment? What's preventing folks from adopting this?

> what do you think about https://tidelift.com/ ?

Tidelift is great!

I'm going to close this issue, since I'm winding down `funding`, but feel free to continue discussion.

**Comment by chrishiestand** [comment]
> Neat project! Looks like you only have 2 open bounties at the moment? What's preventing folks from adopting this?

Well it's new. I'm not sure how long these things take to gain traction. And I'm an engineer, not a marketer so I'm sure I could do better there. Other than that I don't know. Maybe you have some insight? I built it to solve a problem I've experienced many times over, so I would use it. Would you use it? If not, would you share why not?

**Comment by feross** [comment]
I think it's a marvelous experiment. There's a bit of a barrier to entry though. In order to write /boss comments like you show in the video, it seems that I already have to be on the platform with my credit card registered, etc.

How does someone opening an issue know that they need to register and that they can use /boss comments?

**Comment by chrishiestand** [comment]
I agree that can be hard to communicate. I am hoping that the repository owner would be motivated to help make their boss capabilities known. Let me give you a couple scenarios of how I imagine boss would be used:

- `/boss` commands only work on repositories with the [boss github app](https://github.com/marketplace/boss-bounty) installed on them. If installed, the repository owner/package maintainer may then use the `/boss ask $1234` command to request a bounty of $1234 for their time, which will automatically create the boss issue summary which will hopefully make the bounty system much more visible to other visitors of the issue. Other users can also use `/boss ask $x` to put a price on their time to fix the issue. Other than that I do not know of a great way to make it obvious that a GH app is or isn't installed on a given repo's issue. The best I have (and maybe Github has) is to put a badge in the README like so: 
  <img width="90" alt="image" src="https://user-images.githubusercontent.com/100825/64313461-8794d980-cf60-11e9-9060-74023da9408c.png" />
  See the readme of [keel](https://github.com/keel-hq/keel/) for a real life example.
  If the boss github app is installed, _any_ user can use `/boss` commands, but they will only take effect if the user has a boss account in good standing. If they don't, they will get an error message in the boss issue summary comment referring them to sign up/fix it at [https://www.boss.dev](https://www.boss.dev)

- If the boss github application is not installed, `/boss` commands will not work, but bounties may still be created and earned through the [boss.dev](https://www.boss.dev) website. Bounties created on [boss.dev](https://www.boss.dev) can be shared in an issue comment with a badge like so:
  <img width="275" alt="image" src="https://user-images.githubusercontent.com/100825/64313797-b2336200-cf61-11e9-91db-f3486baa95f0.png">

**Comment by feross** [comment]
Great explanation! I'm keen to give this a try at some point!

**Comment by chrishiestand** [comment]
Thanks @feross. I'd love it if you do and I'll be available if you've got any questions or need help with anything.
