### ISSUE TITLE
Can I pay you for an ad-free version?

### ISSUE THREAD

**Issue by christianbundy** [feross/funding#4]
Hey, you did the thing! :heart:

Like I mentioned at dweb camp, I'm super supportive of this, and *if you're interested* I'd be keen for a way to pay $$$ to get an ad-free version of StandardJS. Feel free to close this issue, just wanted to add my "I'd rather give you money than add advertisements to my packages" data point.

Super excited to experiment with this!

**Comment by mixmix** [comment]
Can you imagine how you'd achieve that @christianbundy ?

perhaps a `.fundingkey` file (which you gitignore) which lets funding know you've contributed.... hmm or maybe it checks your npm username ... by hitting the internet. None of these feel great.

**Comment by kethinov** [comment]
For now you can simply [block the ad](https://github.com/kethinov/no-cli-ads) and then [donate to feross here](https://feross.org/thanks/).

**Comment by christianbundy** [comment]
@mixmix 

I was imagining an file in the StandardJS repo that specified which installs should be ad-free. Sponsoring StandardJS with $$$ would get your name added to this file, and during installation it would check your `package.json` and stop giving you ads if it had matching properties name/author/homepage/etc properties. I haven't given this lots of thought, happy for any improvement that aligns incentives to make open source more sustainable.

**Comment by christianbundy** [comment]
Thanks @kethinov, but it's also important to me that this is done with the enthusiastic support of Feross so that we can ensure that it's sustainable for everyone. He does lots of great work and I think this gives us an awesome opportunities to build build systems of reciprocal support and mutual aid.

The problem is systemic, so it's important to me that we can develop *systems* that help tackle the root problem rather than relying on one-off personal actions. :dancing_men::dancing_women:

**Comment by mixmix** [comment]
Very well said changes Christian.
Also great idea for solution

**Comment by modeco80** [comment]
Guess what! You don't need to pay anyone!!!!

With the release of v1.0.8, he has went the French way and now nothing will be displayed no matter what!

**Comment by kemitchell** [comment]
@modeco80 you're harassing a prolific open source contributor from a new account without identifying details. And you just slandered the French.

**Comment by millette** [comment]
@kemitchell I wasn't going to participate, but just wanted to clear something up. When @modeco80 writes
> he has ent the French way
he probably means <https://en.wiktionary.org/wiki/French_exit>
or as the French say
> Filer à l'anglaise

**Comment by kemitchell** [comment]
@millette Thank you for the clarification, and especially for the bit about "Filer à l'anglaise". I may have been mistaken.

Where I grew up, the ahistorical stereotype of Frenchman was military cowardice. I believe we called taking leave without farewell an Irish exit.

Thank you also for typing my language.

**Comment by modeco80** [comment]
> you're harassing a prolific open source contributor from a new account without identifying details.

no

> And you just slandered the French.

The previous guy explained this better than I ever would but it's what he said. No offense.

**Comment by adrianhopebailie** [comment]
cc @matdehaast, @emschwartz, @kof and @cyberdees

@feross and @mixmix  - we're looking at this same problem perhaps we can collab?

We're hoping to build on the ecosystem that is already evolving around [Web Monetization](https://webmonetization.org) whereby websites embed a [Payment Pointer](https://paymentpointers.org) in their site header.

User's have a Web Monetization provider installed in their browser (e.g. [Coil](https://coil.com)'s extension) which sends payments to the website and in return the website doesn't display advertising, provides the user with some premium content, etc.

The same system could work for OSS packages. We were thinking that maintainers could add a Payment Pointer to their package manifest.

By decoupling the way maintainers collect their funds from how users make the payments we leave it up to the users to decide who to pay and how.

Example 1: A company could analyse all of its OSS dependencies and then make a monthly distribution of funding based on a static analysis of their code and how heavily they use dependencies and (their dependencies indirectly).

Example 2: A developer installs a plugin to yarn/npm that monitors their package use and makes payments to maintainers each time the developer installs a package

**Comment by feross** [comment]
I appreciate the thoughtful discussion and feedback. I ended the experiment last week. I shared some thoughts about how the experiment went from my perspective on my blog: https://feross.org/funding-experiment-recap/
