### ISSUE TITLE
How do I delete someone elses repo?

### ISSUE THREAD

**Issue by Joshua-Ashton** [feross/funding#6]
Hi, I don't seem to be able to find the delete button on this repo?
I think my GitHub is bugged...

**Comment by kemitchell** [comment]
I would report this PR as abuse.

https://help.github.com/en/articles/reporting-abuse-or-spam

**Comment by Joshua-Ashton** [comment]
1) It's not a PR
2) Thanks for the block lmfao

**Comment by bermudalocket** [comment]
> * It's not a PR
> * Thanks for the block lmfao

That guy charges $500/hr as a software lawyer but doesn't know the difference between a pull req and an issue lol ok ok ok

**Comment by mixmix** [comment]
Reported as abuse.
